version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=server
      - SERVER_LISTEN_BACKLOG=5
      - SERVER_PORT=12345
    networks:
      testing_net:
        ipv4_address: 172.24.125.2 #server ip DO NOT DELETE COMMENT
    volumes:
      - server-vol:/config

  client:
    container_name: client
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_LOOP_LAPSE=1m2s
      - CLI_LOOP_PERIOD=10s
    volumes:
      - client-vol:/config

    networks:
      testing_net:
        #ipv4_address: 172.24.125.3
    depends_on:
      - server

volumes:
  client-vol:
  server-vol:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.24.125.0/16
